config/routes.rb
Blogapplication::Application.routes.draw do

  root :to => "posts#index"
  
  get "/feeds/posts", :controller => "feeds", :action => "posts", :format => "atom"

  get "/feeds/posts/:id", :controller => "feeds", :action => "comments", :format => "atom"

  resources :shops

  resources :posts do
    resources :comments
    collection do
      get "haml_demo"
    end
  end

  resources :categories

  resources :photos do
    member do
      get 'download'
    end
  end

  resources :attachments do
    member do
      get 'download'
    end
  end


  resources :users  do
    collection do
      get 'login'
      post 'login'
      post 'signup'

      get "logout"
    end

    member do
    end
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  attr_accessible :address, :business_type, :city, :country, :description, :phone, :state, :title
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shops }
    end
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
    @shop = Shop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shop }
    end
  end

  # GET /shops/new
  # GET /shops/new.json
  def new
    @shop = Shop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shop }
    end
  end

  # GET /shops/1/edit
  def edit
    @shop = Shop.find(params[:id])
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(params[:shop])

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render json: @shop, status: :created, location: @shop }
      else
        format.html { render action: "new" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shops/1
  # PUT /shops/1.json
  def update
    @shop = Shop.find(params[:id])

    respond_to do |format|
      if @shop.update_attributes(params[:shop])
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to shops_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :business_type %><br />
    <%= f.text_field :business_type %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing shop</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<h1>Listing shops</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Business type</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Country</th>
    <th>Phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shops.each do |shop| %>
  <tr>
    <td><%= shop.title %></td>
    <td><%= shop.description %></td>
    <td><%= shop.business_type %></td>
    <td><%= shop.address %></td>
    <td><%= shop.city %></td>
    <td><%= shop.state %></td>
    <td><%= shop.country %></td>
    <td><%= shop.phone %></td>
    <td><%= link_to 'Show', shop %></td>
    <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
    <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shop', new_shop_path %>

app/views/shops/new.html.erb
<h1>New shop</h1>

<%= render 'form' %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @shop.title %>
</p>

<p>
  <b>Description:</b>
  <%= @shop.description %>
</p>

<p>
  <b>Business type:</b>
  <%= @shop.business_type %>
</p>

<p>
  <b>Address:</b>
  <%= @shop.address %>
</p>

<p>
  <b>City:</b>
  <%= @shop.city %>
</p>

<p>
  <b>State:</b>
  <%= @shop.state %>
</p>

<p>
  <b>Country:</b>
  <%= @shop.country %>
</p>

<p>
  <b>Phone:</b>
  <%= @shop.phone %>
</p>


<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>