config/routes.rb
Blogapplication::Application.routes.draw do

  root :to => "posts#index"
  
  get "/feeds/posts", :controller => "feeds", :action => "posts", :format => "atom"

  get "/feeds/posts/:id", :controller => "feeds", :action => "comments", :format => "atom"

  resources :shops

  resources :posts do
    resources :comments
    collection do
      get "haml_demo"
    end
  end

  resources :categories

  resources :photos do
    member do
      get 'download'
    end
  end

  resources :attachments do
    member do
      get 'download'
    end
  end


  resources :users  do
    collection do
      get 'login'
      post 'login'
      post 'signup'

      get "logout"
    end

    member do
    end
  end
end

app/views/shared/_footer.html.haml
#footer
  %center
    The BlogApp. CopyRight &copy; #{Time.now.year}. All rights reserved.

app/views/shared/_header.html.haml
#header
  %h2.title The BlogApp HAML

  #nav
    = link_to "Posts", posts_path, :class => ((params[:controller]=="posts" && params[:action]!="haml_demo")? "active" : "")
    = link_to "Categories", categories_path, :class => (params[:controller]=="categories" ? "active" : "")
    = link_to "Photos", photos_path, :class => (params[:controller]=="photos" ? "active" : "")
    = link_to "Attachments", attachments_path, :class => (params[:controller]=="attachments" ? "active" : "")
    = link_to "HAML DEMO", haml_demo_posts_path, :class => (params[:action]=="haml_demo" ? "active" : "")

    #login_links
      - if logged_in?
        = link_to "Logout", logout_users_path
      - else
        = link_to "Login", login_users_path
        = link_to "SignUp", new_user_path