config/routes.rb
Blogapplication::Application.routes.draw do

  root :to => "posts#index"
  
  get "/feeds/posts", :controller => "feeds", :action => "posts", :format => "atom"

  get "/feeds/posts/:id", :controller => "feeds", :action => "comments", :format => "atom"

  resources :shops

  resources :posts do
    resources :comments
    collection do
      get "haml_demo"
    end
  end

  resources :categories

  resources :photos do
    member do
      get 'download'
    end
  end

  resources :attachments do
    member do
      get 'download'
    end
  end


  resources :users  do
    collection do
      get 'login'
      post 'login'
      post 'signup'

      get "logout"
    end

    member do
    end
  end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  attr_accessible :user_id, :file

  belongs_to :user

  has_attached_file :file, 
:path => ":rails_root/private/user_data/:attachments/:id/:filename"

end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController

  before_filter :check_logged_in
  before_filter :get_file, :only => [:download, :destroy]
  before_filter :check_owner, :only => [:destroy, :download]

  private

  def get_file
    @attachment = Attachment.find_by_id(params[:id])
    unless @attachment
      flash[:error] = "Sorry, We couldn't find the requested attachment"
      redirect_to attachments_path
    end    
  end

  def check_owner
    if @attachment.user!=current_user
      flash[:error] = "Sorry, You are not a valid user"
      redirect_to attachments_path
    end
  end
  
  public

  def index
    @attachments = Attachment.where(:user_id => current_user.id)
  end

  def download
    send_file(@attachment.file.path, :filename => @attachment.file_file_name, :disposition => "attachment")
  end

  def new
    @attachment = Attachment.new
  end  

  def show
  end


  def create
    @attachment = Attachment.new(params[:attachment])
    @attachment.user_id = current_user.id
    if @attachment.save
      redirect_to attachments_path
    else
      render :action => :new
    end  
  end

  def destroy
    @attachment.destroy
    flash[:notice] = "Attachment has been removed successfully"
    redirect_to attachments_path
  end

end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/index.html.erb
<h2 class="title">My Attachments</h2>
<%= link_to "Add New attachment", new_attachment_path%>
<br/><br/>

<% unless @attachments.empty? %>
  <ul class="photos_list">
    <% @attachments.each do |attachment| %>
    <li><%= attachment.file_file_name%> <br/>
      <%= link_to "Download this attachment", download_attachment_path(attachment)%>

  <%= link_to "Delete this file", attachment_path(attachment), :method => :delete, :data => {:confirm => "Are you sure you want to permanently delete this attachment?"}%>
    </li>
    <% end %>
  </ul>
<% else %>
  No Attachments Found!
<% end %>

app/views/attachments/new.html.erb
<h2>Add New Attachment</h2>

<div class="form">
  <%= form_for :attachment, :url=> attachments_path, :html => {:multipart => true} do |f| %>
    Select Attachment : <%= f.file_field :file%>
    <br/>

    <%= f.submit "Upload Attachment"%>

  <% end %>
</div>

app/views/attachments/show.html.erb
<%= link_to "View All Attachments", attachments_path%>

<div class="photo">
    <%= @attachment.file_file_name%>
</div>

<%= link_to "Download this Attachment", download_attachment_path(@attachment)%>

<%= link_to "Delete", attachment_path(@attachment), :method => :delete, :data => {:confirm => "Are you sure you want to permanently delete this attachment?"}%>