config/routes.rb
Blogapplication::Application.routes.draw do

  root :to => "posts#index"
  
  get "/feeds/posts", :controller => "feeds", :action => "posts", :format => "atom"

  get "/feeds/posts/:id", :controller => "feeds", :action => "comments", :format => "atom"

  resources :shops

  resources :posts do
    resources :comments
    collection do
      get "haml_demo"
    end
  end

  resources :categories

  resources :photos do
    member do
      get 'download'
    end
  end

  resources :attachments do
    member do
      get 'download'
    end
  end


  resources :users  do
    collection do
      get 'login'
      post 'login'
      post 'signup'

      get "logout"
    end

    member do
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  default_scope :order => "created_at DESC"

  has_many :posts
  
  validates :name, :presence => true, :length => {:minimum => 5, :maximum => 15}

  def self.default
    find_or_create_by_name("Article")
  end

  after_destroy do
    manage_posts
  end

  def manage_posts
    posts.each do |post|
      post.update_attribute(:category_id, Category.default.id)
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :get_category, :only =>[:show, :edit, :update, :destroy]

  private
  
  def get_category
    @category = Category.find_by_id(params[:id])
    if @category.nil?
      flash[:error] = "Sorry, Category not found!"
      redirect_to categories_path and return
    end
  end

  public

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      flash[:notice] = "Successfully created new category!"
      redirect_to categories_path
    else
      render :action => :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes(params[:category])
      flash[:notice] = "Successfully updated the category!"
      redirect_to categories_path
    else
      render :action => :edit
    end
  end


  def destroy
    if @category == Category.default
      flash[:error] = "Sorry, You cannot delete the default category!"
      redirect_to categories_path and return
    end
    @category.destroy
    flash[:notice] = "Successfully deleted the category!"
    redirect_to categories_path
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<% url, method = @category.new_record? ? [categories_path, :post] :[category_path(@category), :put] %>

<div style="padding:10px; background-color:lightyellow; border: 2px solid yellow">
  <%= form_for @category, :url=> url, :method => method do |f|%>
    <%= f.label :name%>
    <%= f.text_field :name%>

    <%= f.submit "Save Category" %>
    <%= button_to "Cancel", :url => categories_path %>
  <% end %>
</div>

app/views/categories/edit.html.erb
<h2>Edit Category</h2>

<%= render :partial => "form"%>

app/views/categories/index.html.erb
<%= link_to "Add New Category", new_category_path %>
<br/>
<hr/>

<% if @categories.empty? %>
  No Categories Found!
<% else %>
  <table>
    <tr>
      <th>Category</th>
      <th>Actions</th>
    </tr>

    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name%></td>
        <td>
          <%= link_to "Edit", edit_category_path(category)%>
          <%= link_to "Delete", category_path(category), :method => :delete, :data => {:confirm=>"Are you Sure?"}%>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/categories/new.html.erb
<%= link_to "View All Categories", categories_path%>
<h2>Create New Category</h2>

<%= render :partial => "form"%>